### ISSUE TITLE
convert_to_unicode

### ISSUE THREAD

**Issue by keithbriggs** [sciunto-org/python-bibtexparser#121]
I am using the 

parser.customization = convert_to_unicode

feature, but in the utf-8 output the accents are coming out on the character before the correct one.  What would cause this?

**Comment by keithbriggs** [comment]
Example: the code below gives output:

Two new books by German scholars: Rudiger Fuchs, Das Domesday Book und sein Umfeld and Jan Gerchow, Die Gedenk̈uberlieferung der Angelsachsen

import bibtexparser
from bibtexparser.bparser import BibTexParser
from bibtexparser.customization import convert_to_unicode

bibtex=r'''
@article{foo,
  author="Anon.",
  title={Two new books by German scholars: Rudiger Fuchs, Das Domesday Book und sein Umfeld and Jan Gerchow, Die Gedenk\"uberlieferung der Angelsachsen},
  journal={Nomina},
  volume={12},
  pages={172},
  year={1988-89},
}
'''

parser=BibTexParser()
parser.customization=convert_to_unicode
bib_database=bibtexparser.loads(bibtex,parser=parser)

for x in bib_database.entries:
  t=x['title']
  print(t)

**Comment by Phyks** [comment]
This is because your bibtex should be written:

```
bibtex=r'''
@article{foo,
author="Anon.",
title={Two new books by German scholars: Rudiger Fuchs, Das Domesday Book und sein Umfeld and Jan Gerchow, Die Gedenk\"{u}berlieferung der Angelsachsen},
journal={Nomina},
volume={12},
pages={172},
year={1988-89},
}
'''
```

or

```
bibtex=r'''
@article{foo,
author="Anon.",
title={Two new books by German scholars: Rudiger Fuchs, Das Domesday Book und sein Umfeld and Jan Gerchow, Die Gedenk{\"u}berlieferung der Angelsachsen},
journal={Nomina},
volume={12},
pages={172},
year={1988-89},
}
'''
```

When typing in BibTeX, the `"` character representing the umlaut is supposed to be *before* the letter. However, when convering to unicode `u+0308` character, this character is supposed to be *after* the letter. Hence, the conversion in `convert_to_unicode` does not work (https://github.com/sciunto-org/python-bibtexparser/blob/master/bibtexparser/latexenc.py#L588).
