### ISSUE TITLE
python package index update

### ISSUE THREAD

**Issue by rudrab** [sciunto-org/python-bibtexparser#159]
Hi,
The pip version is out of date. Is it possible to update it with some newer version?

**Comment by sciunto** [comment]
I don't understand. I can read 0.6.2 on pipy.

**Comment by rudrab** [comment]
yes, but the code is really different. 
check this: https://paste.fedoraproject.org/paste/6UN9zQ4nAdgk2mrCtpnfw15M1UNdIGYhyRLivL9gydE=

**Comment by sciunto** [comment]
Sure, but no release has been made since 0.6.2. There is still some work to do to be able to release a new version. You can checkout this tag https://github.com/sciunto-org/python-bibtexparser/issues?q=is%3Aopen+is%3Aissue+milestone%3A0.7.0 and help if you want. @Phyks is working on it as well.

Thanks. I'm closing this issue.
