### ISSUE TITLE
Prepare release 0.7.0

### ISSUE THREAD

**Issue by sciunto** [sciunto-org/python-bibtexparser#174]
I think we are ready to release 0.7.0.

@omangin and @Phyks  do yu see anything to fix before? There's one task left, which can be done later imho.

**Comment by Phyks** [comment]
Huge :+1: for 0.7.0! :) I think we might be able to release a 0.8.0 quite soon afterwards, merging (or discarding) the remaining PRs (such as splitnames features etc), and doing some quick fixes listed in issues.

One thing we should fix before 0.7.0 IMHO is https://github.com/sciunto-org/python-bibtexparser/issues/171 I think, which boils down to writing some doc on customizations and `alt_dict`, so that we could close it (matching code to replace `link` by `url` has already been merged).

**Comment by seisman** [comment]
Any progress on this release?

**Comment by benureau** [comment]
@omangin and I are starting to exploit the functionality of the new code (for instance here: https://github.com/pubs/pubs/pull/116), but without a release, there are no reasonable ways for us to make the installation easy of our users via pip. A new release would be of great use to us.

**Comment by sciunto** [comment]
I promised a release for today :) v1.0 is out !

**Comment by benureau** [comment]
@sciunto thank you!
