### ISSUE TITLE
Bibtex Strings question

### ISSUE THREAD

**Issue by NanoExplorer** [sciunto-org/python-bibtexparser#201]
Hello, I can't find much information about the implementation of bibtex strings on the readthedocs site. I have been parsing BibTex files generated by NASA ADS, for example [this Ph.D. Thesis](https://ui.adsabs.harvard.edu/#abs/2008PhDT.........1N/abstract). If you go to the left panel and choose export... in BibTex, you will notice that it includes the line
`month = January`, which crashes the BibTexParser even when `common_strings=True`. What is the recommended way to work around that? Appending `@string` sections to the top of the BibTex for each month seems to work. I also tried making my own set of string definition tuples and adding them manually (see the following code). Which method is more future-proof? 
```python
monthstrings = [('january','January'),...]
parser = bibtexparser.bparser.BibTexParser(common_strings=True)
parser.bib_database.strings.update(monthstrings)
```

My other question relates to how the library writes bibtex files. For me it will write either `month={January}` or `month={jan}` and I can't tell how it chooses one or the other. Is there a way for me to standardize everything to `month = jan`? I'm guessing that when there are brackets around the month it is being treated as a raw string instead of a bibtex string, so if the parser reads in `month={jan}` it will write out `month={jan}` but if it reads in `month = jan` it will write out `month={January}`.

Thanks in advance for your help!

**Comment by omangin** [comment]
Hi @NanoExplorer. There is some doc on the strings there: https://bibtexparser.readthedocs.io/en/master/tutorial.html#using-bibtex-strings. It is probably not perfect so feel free to help us improve it!

The reason why the example bibtex does not work is because it is not correct bibtex. As you wrote, `month = January` refers to the value of the bibtex string `January` while it is not defined. On the other hand `month = {January}` is a literal value.

We added the commodity of `common_strings` because these are very common for months and often a way to also provide some king of internationalization. Activating the option is a good mitigation to get the software to work out of the box for most bibtex files.

Loading your own set of stings is indeed the correct way to have the behavior you want, at least for being able to replace the strings by their value in the bibdata. This is controlled by the option `interpolate_string`, which defaults to `True`. Using the option is convenient and compatible with the export code (`bwriter`). It results in something like `month = {January}` being output (the string is replaced by its value). The downside is that the parser does not retain the information about a string being use in the value for the `month` attribute.

You may disable the option to retain this information. However, the support for strings in the writer is not yet implemented so you won't be able to export the bibdata that way. (I have just opened #202 regarding this.)

Also, one way to handle the issue would be to have an option to handle undefined strings without errors. These would be replaced by their name if we need to print some attribute values where they appear and on this would enable to export the bibtex as it was read. I have openned  #203 regarding this.

**Comment by alan-isaac** [comment]
Also see [#203](https://github.com/sciunto-org/python-bibtexparser/issues/203).
