### ISSUE TITLE
Not throwing exception on error?

### ISSUE THREAD

**Issue by benureau** [sciunto-org/python-bibtexparser#211]
Hi, I have noticed that the current master does not throw PyParsing error anymore on some incorrect input: for instance,
```
from bibtexparser.bparser import BibTexParser

btp = BibTexParser()

print(btp.parse('@misc{I am not a correct bibtex{{}', partial=False).get_entry_dict())
```
just returns the empty dict right now. Is that normal? What do I have to do to get a parsing error that can give feedback on what went wrong?

Oh, the `BibTexParser(bibstring)` behavior is not documented (or announced deprecated), and does not accept the `partial` argument: it probably should. One way or the other, this just seems confusing right now.

**Comment by omangin** [comment]
See also #163 and #212.

the way the parser is implemented right now is to consider blocks that could not be parsed as implicit comments. Because of that, the parser silently ignores most failures while parsing.

I believe this is indeed not a really desirable behavior and we should probably change the default to something stricter (eventually having a `permissive_implicit_comments` option if deemed necessary). The remaining question is what should then be considered an implicit comment?

In my opinion a reasonable answer would be anything not starting by `@alpha{`.

Any thought on this?

**Comment by andres-fr** [comment]
Hi!

First of all thanks a lot for the pointers and the amazing functionality that bibtexparser provides.

For many weeks now, I've been curating a dataset involving bibtex entries, and for that I've been using bibtexparser. After some random checks I've found out that faulty entries are silently ignored. This was a very unpleasant surprise, because I don't really know how much of the dataset I've actually been missing along the way.

I couldn't figure this out after reading through the docs, then I went to the issues and found this one. Do you know any way (API, other libs, changing lib code, anything) to fix this? If there is a possible fix within the lib I'll be happy to give it a shot and submit a PR. Just let me know!

Now to a small constructive rant: In my situation, and probably in most others, it is fundamental to know if the data is corrupt, and I agree with the above comment that silently ignoring exceptions is not really a desired behaviour. But more importantly, it isn't an *expected* behaviour: Even if it was desired, users should definitely be informed about this! I'd suggest to add information about the current behaviour to the README or somewhere visible ASAP, this is way too relevant to be relegated to issue discussions.

Cheers,  
Andres

**Comment by tyarosevich** [comment]
I've encountered similar silent exceptions like this when it encounters unicode characters it doesn't know how to handle. In one case, a logging action from line 31 of bibtexexpression.py was actually logging the entire file as it was parsed, using my logging.basicConfig and dumping the whole thing in my error log file. This was difficult to debug. This might relate to a broader issue with unicode characters, but I thought I'd chime in as more explicit error handling would have been helpful here in my opinion.

P.S. I'd like to echo Andres, thank you for writing this library, it's been a huge help.

**Comment by sciunto** [comment]
Thanks for your acknowledgements. Unfortunately, I do not have the bandwidth to maintain this package anymore (as stated in the readme file). If someone wants to take care of it, I'm ready to provide what's necessary (access, whatever).

**Comment by andres-fr** [comment]
Dear @sciunto,

Thank you very much for your answer, I totally understand the situation. I'll try to get a PR with the following done over christmas:

1. Modify package to optionally raise exceptions for data errors (default behaviour: ON)
2. Update documentation
3. Roll out a new (minor?) version to PIP, check autodocs&TravisCI are consistent.

I'll try to get this done, maintenance would be probably too much for me as well.
What do you think about this? Any tips where to look for point 1?
Thanks again for your contributions and consideration.

Best regards,
Andres

**Comment by andres-fr** [comment]
@ibe-314 unfortunately I didn't get around to do it, and iirc i didn't figure out a strategy either back then, but what you propose looks reasonabe to me, I'd say go for it!

**Comment by MiWeiss** [comment]
Hi @ibe-314 

Thanks for posting the snippet. The swallowing of errors is a major issue and I am happy that you found a workaround that works for your use case. 

What regards the `strict` parameter you proposed for the `BibTexParser`, I guess I'd be reluctant to merge such a PR: Implicit comments are a defined part of valid bibtex (and bibtex variants). Thus, failing parsing whenever there's an implicit comment would be quite unexpected. Thus I'd propose you continue with the subclass you proposed :+1: 

I am afraid a clean solution is still a bit further away - but not quite as far as it once was: I have started drafting BibTexParser 2.0 which uses a fundamentally different parsing approach, which amongst other advantages would allow raising warnings whenever an implicit comment looks suspicious.

**Comment by ibe-314** [comment]
Thank's for the information. Then I will use my workaround until BibTexParser 2.0 will be published :-)

**Comment by MiWeiss** [comment]
V2 beta is now available (install from main branch). It creates "ParsingFailedBlocks". After parsing checking for the presence of such blocks allows to check for errors and their causes, without disabling the parsing of other blocks.
