### ISSUE TITLE
Confusing option setting for the parser

### ISSUE THREAD

**Issue by omangin** [sciunto-org/python-bibtexparser#224]
Some options have to be set when the parser object is created like `common_strings` because they are treated in the `__init__`, others can be changed until the parsing occurs by doing some `parser.option = new_value`.

This behavior is confusing and should be improved to convey more clearly what the parser object does and retain. It is not clear which approach to this is best: loading default strings could be delayed to just before parsing, or setting options directly could be deprecated.

See also #222.

**Comment by turab95** [comment]
Another option is to add a setter function for `common_strings` that calls `load_common_strings()`. I think this is better than loading the strings before parsing, although it's a little ugly syntactically.

**Comment by tqbl** [comment]
True, but wouldn't this also be a problem if you loaded the strings before parsing? In principle, the user could set it to false after parsing once and then try to parse again.

Without fully checking the source code, adding `self.bib_database.strings = OrderedDict()` for the second statement should work. It would override strings added due to previous parse actions, but shouldn't lead to errors.

**Comment by omangin** [comment]
Indeed but it requires the user to know and interact with what is supposed to be implementation details.

Here I would say that if we want to allow that we should provide a method for resetting the string database instead.

**Comment by MiWeiss** [comment]
fixed in v2
