### ISSUE TITLE
Fails to parse month entry 'jan'

### ISSUE THREAD

**Issue by HDembinski** [sciunto-org/python-bibtexparser#280]
The parser fails to parse the month in entries like this which come from a widely used standard repository maintained by Harvard, see adsabs.harvard.edu

```
@INPROCEEDINGS{2001ICRC....3..985D,
       author = {{Desiati}, P. and {AMANDA Collaboration}},
        title = "{Analysis of atmospheric muons with AMANDA}",
    booktitle = {International Cosmic Ray Conference},
         year = 2001,
       series = {International Cosmic Ray Conference},
       volume = {3},
        month = jan,
        pages = {985},
       adsurl = {https://ui.adsabs.harvard.edu/abs/2001ICRC....3..985D},
      adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bibdatabase.py", line 107, in expand_string
    self.strings[name])
KeyError: 'jan'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bibtex", line 33, in <module>
    sys.exit(load_entry_point('autobib', 'console_scripts', 'bibtex')())
  File "/Users/hdembinski/Extern/autobib/autobib/__init__.py", line 29, in main
    db = util.load(f)
  File "/Users/hdembinski/Extern/autobib/autobib/util.py", line 16, in load
    return parser.parse_file(fo).entries
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bparser.py", line 169, in parse_file
    return self.parse(file.read(), partial=partial)
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bparser.py", line 147, in parse
    self._expr.parseFile(bibtex_file_obj)
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bibtexexpression.py", line 278, in parseFile
    return self.main_expression.parseFile(file_obj, parseAll=True)
  File "/usr/local/lib/python3.8/site-packages/pyparsing.py", line 2577, in parseFile
    return self.parseString(file_contents, parseAll)
  File "/usr/local/lib/python3.8/site-packages/pyparsing.py", line 1943, in parseString
    loc, tokens = self._parse(instring, 0)
  File "/usr/local/lib/python3.8/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/local/lib/python3.8/site-packages/pyparsing.py", line 4781, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/usr/local/lib/python3.8/site-packages/pyparsing.py", line 4707, in parseImpl
    loc, tmptokens = self_expr_parse(instring, preloc, doActions)
  File "/usr/local/lib/python3.8/site-packages/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/usr/local/lib/python3.8/site-packages/pyparsing.py", line 4254, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/usr/local/lib/python3.8/site-packages/pyparsing.py", line 1716, in _parseNoCache
    tokens = fn(instring, tokensStart, retTokens)
  File "/usr/local/lib/python3.8/site-packages/pyparsing.py", line 1316, in wrapper
    ret = func(*args[limit[0]:])
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bparser.py", line 187, in <lambda>
    lambda s, l, t: self._add_entry(
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bparser.py", line 277, in _add_entry
    d[self._clean_field_key(key)] = self._clean_val(fields[key])
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bparser.py", line 228, in _clean_val
    return as_text(val)
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bibdatabase.py", line 270, in as_text
    return text_string_or_expression.get_value()
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bibdatabase.py", line 231, in get_value
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bibdatabase.py", line 231, in <listcomp>
    return ''.join([BibDataString.expand_string(s) for s in self.expr])
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bibdatabase.py", line 197, in expand_string
    return string_or_bibdatastring.get_value()
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bibdatabase.py", line 178, in get_value
    return self._bibdatabase.expand_string(self.name)
  File "/usr/local/lib/python3.8/site-packages/bibtexparser/bibdatabase.py", line 109, in expand_string
    raise(UndefinedString(name))
bibtexparser.bibdatabase.UndefinedString: 'jan'
```

How can this be fixed?

**Comment by pszolovits** [comment]
I believe your problem is that common_strings defaults to False, whereas you need True in order to include bare string like jan. I use code such as:
<pre>
with open(source_file) as bibtex_file:
    parser = BibTexParser(common_strings = True)
    bd = bibtexparser.load(bibtex_file, parser=parser)
</pre>
and then it works.

**Comment by psawa** [comment]
I had the same problem, months couldn't be parsed. Looking at the code, I draw the same conclusion as @pszolovits. 

However I believe the problem here is in `bparser.py` line 90 : 

```py
        #: Load common strings such as months abbreviation
        #: Default: `False`.
        self.common_strings = common_strings
        if self.common_strings:
            self.bib_database.load_common_strings()
```

The common strings are loaded if the common string definition is included, but shouldn't it be the opposite? Load the common strings if none is provided. 

In any case making the change in the code did the work. I'll submit a PR

**Comment by CAMOBAP** [comment]
@pszolovits thanks, just checked and it works.

Maybe there is a way to generate BiBTeX with common_strings to produce `month` like `jan` instead `{jan}`?

I have tried:

```
parser = BibTexParser(common_strings=True)
bt = bibtexparser.loads(bibtex, parser)
```

Unfortunatelly it doesn't work

**Comment by cromlyngames** [comment]
I just hit this same issue. 

the issue seems to be in the helper function bibtexexpression.py  def _strip_after_new_lines(s) 
https://github.com/sciunto-org/python-bibtexparser/blob/master/bibtexparser/bibtexexpression.py  line 9.

I amended mine to paste out the value of 's' and it's type. The expected type is string.

As an example, this bibtext produced the following output: 

input
`@Book{jabi2013parametric,
 author = {Jabi, Wassim},
 title = {Parametric design for architecture},
 publisher = {Laurence King Publishing},
 year = 2013,
month = jan,
 address = {London},
 isbn = {978-1780673141}
 }
 `

gives the following types before stopping due to errror

`Jabi, Wassim <class 'str'>
Parametric design for architecture <class 'str'>
Laurence King Publishing <class 'str'>
2013 <class 'str'>
BibDataString('aug') <class 'bibtexparser.bibdatabase.BibDataString'>`


### Confirmed expected behaviour
Any line in the bibtext enclosed in curly brackets (or quotation marks) was passed through as a string. 
A year without curly brackets was passed through as a string
Numerical months without curly brackets were passed through as a string
Three letter acronym months with curly brackets were passed through as a string

### unexpected behaviour
Three letter acronym months **without** curly brackets were passed through as a BibDataString with no splitlines function
one article with the unusual format 'number = C7,'  (without curly braces) also failed, and worked once put in curly braces


### manual workaround
1) search through bibtex file for month and wrap them in curly brackets or replace with the number. This covers 99% of cases
2) add print(s, type(s))  to the _strip_after_new_lines(s): function to help manually find any errors that remain

I tried unsuccessfully adding some type based error handling in the function, but BibDataString.get_value() still returns in type BibDataString, and really it feels like it should be handled upstream of this function.



It's a more general case of https://github.com/sciunto-org/python-bibtexparser/issues/263

https://github.com/sciunto-org/python-bibtexparser/issues/249 may also be related.

**Comment by cappelletto** [comment]
Hi, I had the same issue when trying to parse with a `BibTexParser` object with the `common_strings=True`, which was expected to be able to parse the month entry without curly brackets.
The only way I have been able to load & parse it is by disabling the `interpolate_strings` option in the parser object as hinted [here](https://bibtexparser.readthedocs.io/en/master/tutorial.html#using-bibtex-strings). The resulting call is:

```

from bibtexparser.bparser import BibTexParser
from bibtexparser.bibdatabase import as_text    # helper to expand entry to text if we want to print or export it

parser = BibTexParser(common_strings=True, interpolate_strings=False) # create parser object, with capability to process non-string month field (valid in Latex)

with open('sample.bib') as bibtex_file:     # open the bibtex file to be processed
    bibtex_str = bibtex_file.read()         # read as string, the we process it with the parser object

bib_database = parser.parse(bibtex_str)     # parse the bibtex string

print (bib_database.entries[0])
print (as_text(bib_database.entries[0]['month']))
```
 

Needless to say, user your own `sample.bib` file that was causing the issue and modify the entry number - if necessary. Also, it is necessary to be careful when exporting the fields (e.g. writing to another file) as you may require to use the `as_text()` helper function.
