### ISSUE TITLE
`@CONTROL{REVTEX41Control}` statement ignored

### ISSUE THREAD

**Issue by tovrstra** [sciunto-org/python-bibtexparser#384]
The [AIP LaTeX template](https://www.overleaf.com/latex/templates/template-for-submission-to-aip-publishing-journals/xhsskcchtbxf) produces an extra bib file, typically named `articleNotes.bib` (when the main tex file is `article.tex`). It contains the following two lines:

```bibtex
@CONTROL{REVTEX41Control}
@CONTROL{aip41Control,pages="1",title="0"}
```

The first line seems to be ignored by python-bibtexparser, while `bibtex` can properly handle it.

Minimal example to reproduce the issue:

```python
import bibtexparser
btp = bibtexparser.bparser.BibTexParser(ignore_nonstandard_types=False)
print(bibtexparser.load(open("articleNotes.bib"), btp).entries)
```

This only prints out the entry corresponding to the second control line:

```python
[{'title': '0', 'pages': '1', 'ENTRYTYPE': 'control', 'ID': 'aip41Control'}]
```

**Comment by MiWeiss** [comment]
Ouw, thats interesting!

Currently, `@CONTROL` blocks as described above are not supported. To be honest, I was not even aware of them. I am - in general - in favor of adding the corresponding functionality if it turns out to be something standard. However, I was on a short search not able to find any specification describing the `@CONTROL` block specs.

Note: The reason the first line was not parsed, but the second one was is simple. For unknown block types, bibtexparser assumes they are entries (if the `ignore_nonstandard_types=False` is set in v1) such as `@article`. The first line then does not match the expected schema for a entry block. 

Could you provide me with some link to `@CONTROL`? specs? I'll then consider addition of them.

**Comment by tovrstra** [comment]
The `@CONTROL` is not defined in the BibTeX documentation. It's something specific to the AIP [RevTeX template](https://journals.aps.org/revtex) ([documentation at CTAN](https://www.ctan.org/tex-archive/macros/latex/contrib/revtex)). It's mainly used for version checking and setting some RevTeX-specific options.

I believe the issue is not specific to `@CONTROL`. In general, even if it seems useless at first, BibTex tolerates entries without tags. I did not find documentation for it, but it is easily verified with the following inputs:

In `test.aux`:

```
\citation{SomeName2023}
\bibdata{test}
\bibstyle{unsrt}
```

In `test.bib`:

```
@customentry{SomeName2023}
```

Running `bibtex test.aux` produces the following `test.bbl`:

```
\begin{thebibliography}{1}

\bibitem{SomeName2023}


\end{thebibliography}
```

The standard output contains a few warnings, but no errors:

```
This is BibTeX, Version 0.99d (TeX Live 2022/CVE-2023-32700 patched)
The top-level auxiliary file: test.aux
The style file: unsrt.bst
Database file #1: test.bib
Warning--entry type for "SomeName2023" isn't style-file defined
--line 1 of file test.bib
Warning--all relevant fields are empty in SomeName2023
```

I'm not sure where the BibTeX format is officially and formally documented. Assuming [https://www.bibtex.org/Format/](https://www.bibtex.org/Format/) is authoritative, only `@STRING`, `@PREAMBLE` and `@COMMENT` should not be treated as entries. It does not say that all other ones must be entries, but one could argue that it is implied.

**Comment by MiWeiss** [comment]
Thank you, this makes sense.

#385 will close this for v2 (beta, see README.md). For `v1` the parsing pattern will have to be adapted. I don't think the changes will be major, but I won't personally invest in it. 

If interested, feel free to open a PR and I'll happily review.
