### ISSUE TITLE
1.4.1 has version 2.0.0b3

### ISSUE THREAD

**Issue by mgorny** [sciunto-org/python-bibtexparser#409]
**Describe the bug**
The 1.4.1 tag points at a commit that specifies the version in `setup.py` as 2.0.0b3.

**Reproducing**

https://github.com/sciunto-org/python-bibtexparser/blob/12678c5fe30b328ad7b36e88ec9732258cc150fc/setup.py#L4

**Workaround**
n/a

**Remaining Questions (Optional)**
Please tick all that apply:

- [ ] I would be willing to to contribute a PR to fix this issue.
- [x] This issue is a blocker, I'd be greatful for an early fix.

**Comment by MiWeiss** [comment]
Ouch. Thanks a lot for reporting.

As I see it, the problem is only regarding the tag on github, but not the deployed version on pypi.

When creating / deploying the release (which is not automated for v1) I seem to have built and deployed from the correct `v1` branch, but then tagged and github-released from the main branch. This is now corrected.

**Comment by mgorny** [comment]
Thanks!
