### ISSUE TITLE
[RFC] string representation

### ISSUE THREAD

**Issue by sciunto** [sciunto-org/python-bibtexparser#98]
Original comment from @omangin in #64.

So I believe the conclusion is that we have to accept common strings by default. (That is `common_strings=True` as the default value for the parser.)

Then comes a new question. Currently the new parser uses a special object from `bibdatabase.py` called `BibDataString` to represent parsed string object. This, in theory, enables to delay the interpolation of bibtex strings and chose, for example, to later write it as such in a new file. It seems that the current parser by default interpolates strings and that the default interpolation content for undefined strings is the key. This means that `month = jan` is parsed into `'month': 'jan'` which would be exported as `month = {jan}` by the writer. Then I guess bibtex itself would not interpolate "jan" since it is not parsed as a string name any more.

What is yet implemented for the new parser is to interpolate known strings ("known" meaning previously defined in the bibtex file or being a common string if the option is set). This is close to the previous behavior but not exactly the same since unknown strings raise errors.

So here are the options to implement:
- the clever way: represent string expressions as such (lists of python `string` and `BibDataString`). This unables the interpolation as well as the export in the original form. This however breaks the compatibility with the current behavior. (Although it is possible to hack these _bibtex string expressions_ to behave as python string.) 
- the always working solution: always interpolate. This would be fully compatible with previous behavior with the aforementioned issue.
- the strict option: fail on undefined strings, either interpolate or keep the full structure.

I think that the interpolation fits well as a customization function where I should move it. The other solutions are all easy to implement but might break some compatibility. What do you think should be the default?

**Comment by omangin** [comment]
As an additional comment: if we want the original file to be preserve by application of the parser and writer, we need to keep the structure of the string expressions. For that reason I think that string interpolation belongs to customization functions.

**Comment by omangin** [comment]
I made some refactoring to bring all string interpolation to `bibdatabase.py`. Also added some tests. This does not change the behavior of the parser but should make it simpler to implement the chosen solution (once chosen).

omangin/python-bibtexparser@9c2ee50275

**Comment by sciunto** [comment]
I think we should move to a result that looks like `month = jan`. I'm convinced this is what users are expecting. It's also better to be able to write a bibtex with strings defined in the original file.

The interpolation could happen either through an option or a customization. I do not have a strong feeling of the best solution for now. I also do not have much concern about API breakage until we reach 1.0.

**Comment by sciunto** [comment]
About option vs customization. Customization were originally designed to alter content between `{ }`. Here, its more about the representation of the structure. Conceptually, it's probably a little bit different.

A use case I imagine a code that takes a bibtex and render it in html. Interpolation is the business of the developer, while a customization is something that can be proposed to the user through an API made by the dev of that application.

That argument would vote for an option.

**Comment by sciunto** [comment]
@omangin Do you have some time to iterate on this? This is the most critical issue to solve for the next release that I would like to do quite soon.

**Comment by omangin** [comment]
Sorry for not answering earlier. I did not have so much time recently. So if I sum up correctly:
- we need an option to turn on/off string interpolation at parse time,
- the default will become `False` and will require to update a lot of tests,
- if strings are not interpolated we keep the `BibDataStringExpression` representation until the values are written to a new bibtex file,
- we need the adequate mechanisms in the writer. This implies in particular deciding whether and which string definitions should be written to the output file (for example should we write the months definitions? do we need an option for that?), as well as doing it.

I'll start working on the first part and keep the branch https://github.com/omangin/python-bibtexparser/tree/feat/better-strings up to date. Or maybe should I move it to the main repository?
Feel free to start adding unit tests to better define how the code should behave for the second part.

**Comment by sciunto** [comment]
All of this sounds good to me. 

About the writer, I don't think we need to write the definitions. However, an option could not hurt. It's just a for loop at the end. So +1 for that.

For the repository, you can keep your branch and open a PR so that we can check travis' status. Also, I can make PR against your branch that way and two pairs of eyes are often useful. I'll start editing the tests.

Thanks!

**Comment by joelfrederico** [comment]
Any progress on this? It's holding me up right now. I'm using bibtexparser to automatically parse and fix the (god-awful) output Mendeley gives me.

**Comment by sciunto** [comment]
@joelfrederico Sorry, I have a lot of coding duties. If you have some time to look at it, I'm ready to review PRs.

Thanks!

**Comment by Phyks** [comment]
Related: #47, #152.

**Comment by Phyks** [comment]
@sciunto @omangin I have some time to try to have a look at this issue, but I am not sure I understand precisely everything that should be done (mainly since I haven't used BibTeX string yet).

As far as I understood, `month = jan` means `jan` will be replaced by the string declaration (`@string{jan = "foobar"}`), if any. If no string is previously defined, it is handled as a braced string by BibTeX (and this is failing at the moment in bibtexparser with a `KeyError`.

Is https://github.com/omangin/python-bibtexparser/commit/31082f625c97b05dd807df6e80e9bc69dfdfe046 still a good starting point?

If I understood correctly:
* There should be an option to turn on/off string interpolation.
    * If string interpolation is on, we just use the current behavior.
    * If string interpolation is off, we need to keep some representation of the string, until they are written in a file. How should they be written? (Braced? Or as they were in the original file?)

Also, should not bibtexparser return a more explicit exception than `KeyError` in case a string definition is missing?

Thanks!

**Comment by sciunto** [comment]
To answer your first question, I don't think it should be braced but left as it was originally.
For your second question, yes.

**Comment by Phyks** [comment]
Ok, I'll try to have a look at it :)

**Comment by omangin** [comment]
Hi @Phyks. Sorry to come back late again! I have actually done a little more on this topic. I just updated the branch [omangin/python-bibtexparserfeat/better-strings](https://github.com/omangin/python-bibtexparser/tree/feat/better-strings) accordingly.

It includes the replacement of `KeyError` by something more explicit (`UndefinedString`). Actually it might be better to call it `UndefinedBibDataString` to avoir confusion.

Currently it uses a custom class `BibDataStringExpression` to represent the expressions. Internally it is just a  list of strings and `BibDataString` (it's actually annoying that both are called string ;) ). I am not 100% happy with the way it is implemented now because we can either have values represented as `string` or `BibDataStringExpression` and having to test for the type of object might be error prone (code assuming strings would work with the default setting but fail when interpolation is turned off).

Once again we could replace strings by a custom class to provide a similar interface to the expression class. However in my opinion a simpler approach would be to simply implement the `__str__` method of the `BibDataStringExpression`.

The following still remains to implement:
– `bwriter` compatibility (this should be straightforward),
– compatibility with customization functions,
– check for recursive string definitions: currently string definitions can include string expressions which allow for recursion. We could leave that to be caught at run time as a `RecursionError` or implement a test to be able to throw an exception when parsing. The test could either be explicit (searching the tree of expressions) or just try to interpolate all string definitions and catch the `RecursionError`. The latter is quicker to implement and only  takes longer to execute when their is actually a recursion.

Please fill free to comment any of this elements or the code itself.
Thanks

**Comment by Phyks** [comment]
Thanks for all the info! I am quite busy at the moment, but will have a look at it ASAP to merge it and close this issue. :)

**Comment by omangin** [comment]
I just created a PR with the added implementation of the `bwriter` compatibility and tests.

Regarding customization functions, it's not clear how to do that other than in a case by case basis. It might be worth adding some documentation to state that except otherwise noted, customization functions are to be expected not compatible with string representations. It might then worth porting a few ones, by using the [`apply_on_strings` method](https://github.com/omangin/python-bibtexparser/blob/feat/better-strings/bibtexparser/bibdatabase.py#L186) for bibtex expressions.

**Comment by omangin** [comment]
Merged #165. Please comment here for any improvement or suggestions on the handling of string representations.

**Comment by Phyks** [comment]
I think we can close this one and reopen if any problem appear, no?
